# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.5

pipelines:
  branches:
    master:
      - step:
          script: # Modify the commands below to build your repository.
            - pip install "awscli>=1.11,<1.12"
            - sed -i -e "s/{{ datetime }}/`date \"+%Y-%m-%d %H:%M:%S%z\"`/g" __version__.json
            - sed -i -e "s%{{ commit_hash }}%${BITBUCKET_COMMIT}%g" __version__.json
            - mkdir html
            - cp -rf __version__.json index.html www_index.css www_index.js gpg media html/
            - aws s3 cp --recursive html s3://www.ho600.com/
            - aws s3 sync --delete html/gpg/ s3://www.ho600.com/gpg
            - sed -i -e "s/{{ datetime }}/`date \"+%Y-%m-%d %H:%M:%S\"`/g" pipeline-messages.json
            - sed -i -e "s/{{ commit_hash }}/${BITBUCKET_COMMIT}/g" pipeline-messages.json
            - aws ses send-email --destination file://pipeline-destination.json --message file://pipeline-messages.json --region us-west-2 --from service@ho600.com 